let suggestions = [
    "12C Hazina",
    "2B Travellers",
    "Aldana Travellers",
    "Allsops Travellers",
    "Astrabell",
    "Baba Ndogo 25",
    "Buruburu 58",
    "CBET Sacco",
    "Citi Hoppa",
    "City Star",
    "City Tram",
    "City Travellers",
    "DABUMATO COMMUTER SERVICE SACCO",
    "EASTERN BYPASS SACCO LTD",
    "EASTLEIGH COMMUTER SERVICES LIMITED",
    "EASTLEIGH ROUTE SACCO CBD",
    "FORWARD TRAVELLERS SACCO",
    "GITHURAI 45 SACCO",
    "HIGHRISE KIBERA SACCO CBD",
    "HURUMA 46 SACCO LTD",
    "KAKA TRAVELLERS SACCO",
    "KENYA BUS SERVICE",
    "KIAMBU MARAFIKI SACCO",
    "LOPHA MULTIPURPOSE",
    "MWIKI PSV SACCO CBD",
    "NAWASUKU SACCO",
];